<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class UtilityRatingViewTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->post('login', [
            'email' => 'superuser@corals.io',
            'password' => '123456',
        ]);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_utility_rating_view()
    {
        $response = $this->get('utilities/ratings');

        $response->assertStatus(200)->assertViewIs('utility-rating::index');
    }

    public function test_utility_rating_bulk_action()
    {
        $response = $this->post('utilities/ratings/bulk-action', [
            'action' => 'pending',]);


        $response->assertSeeText('message');
    }
}
