<?php

namespace Tests\Feature;

use Corals\UtilityRating\Models\Rating;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UtilityRatingViewTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->post('login', [
            'email' => 'superuser@corals.io',
            'password' => '123456'
        ]);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_utility_rating_view()
    {
        $response = $this->get('utilities/ratings');

        $response->assertStatus(200)->assertViewIs('utility-rating::index');
    }
}
