<?php

namespace Tests\Feature;

use Corals\User\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class UtilityRatingViewTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::query()->whereHas('roles', function ($query) {
            $query->where('name', 'superuser');
        })->first();
        Auth::loginUsingId($user->id);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_utility_rating_view()
    {
        $response = $this->get('utilities/ratings');

        $response->assertStatus(200)->assertViewIs('utility-rating::index');
    }

    public function test_utility_rating_bulk_action()
    {
        $response = $this->post('utilities/ratings/bulk-action', [
            'action' => 'pending',]);


        $response->assertSeeText('message');
    }
}
